### PR TITLE
Default to remote .ruby_version

### PR DESCRIPTION
**Pull request by flori**

### CODE REVIEW

**Comment by kirs** [comment]
Well, I intentionally left declaration of ruby version in deploy recipe because IMO that would make it more explicit.

**Comment by kirs** [comment]
I'm open to change it, but it would be good to have a reason to.

**Comment by flori** [comment]
I had the following problem with this: if you do something like

$ BRANCH=new_release cap production deploy

but you have checked out the master branch atm, it's possible that the ruby version is set to the one in the master branch. However, what you actually wanted was the ruby version set in the new_release branch. By using the version defined in .ruby-version on the remote system that shouldn't happen anymore. Howerver, if you explicitly set a version it is still used like it was before.

Another way to be more explicit would be to require the user to set the version to :remote in order for capistrano to pick the remote version. Maybe it would also be possible to set it to :local so the local version of .ruby-version is picked. This would at least avoid having to define the ruby version at two different places.

**Comment by jarmo** [comment]
I solved the problem like this:
```ruby
# config/deploy.rb

set :chruby_ruby, File.read(File.expand_path("../.ruby-version", __dir__)).strip
```

I think that `capistrano-chruby` should not rely on `.ruby-version` automatically unless `chruby/auto.sh` has been loaded. In other words - `.ruby-version` should be only used when `chruby` normally uses that.

**Comment by flori** [comment]
@jarmo The problem with this is that you read the local .ruby-version file, but the deploy branch might have another ruby configured via .ruby-version.

At the moment I use this method to fetch the file directly from git

    def ruby_version
      @ruby_version ||= `git show #{fetch(:branch)}:.ruby-version`.chomp
    end

and later

    set :chruby_ruby, ruby_version

**Comment by jarmo** [comment]
Yeah, okay, but that solution was sufficient for my case since i'm deploying master. I'm also using same Ruby version in production and locally, which is always a good idea.

**Comment by kirs** [comment]
The solution suggested by @flori in comments is the most bulletproof, but we obviously can't include it into the gem because we have to stay SCM-agnostic.

**Comment by speckins** [comment]
A slight modification to the method @flori proposed: using a proc for "set :chruby_ruby" means you can put it centrally in config/deploy.rb, and if you use different branches in your config/deploy/*.rb stages, it will be evaluated after "set :branch".

    # config/deploy.rb
    set :chruby_ruby, -> {
      `git show #{fetch(:branch)}:.ruby-version 2>/dev/null`.chomp.presence || 'system'
    }

    # Capfile (if you use the handy #presence method)
    require 'active_support/core_ext/object/blank'

**Pull request closed without merging**
