### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by kirs**
Fixes https://github.com/capistrano/chruby/issues/11

Sorry that I forgot to add license to the project.
I added MIT license since it's used by most of other capistrano/ projects.

### CODE REVIEW

**Comment by kirs** [comment]
This project had 6 contributors. Does anyone know how the procedure of adding a missing license works? Do we need to get an agreement from each contributor, like in the case of switching license?

**Comment by clemens** [comment]
According to choosealicense.com, "No License" means that you can't just add a license later on (see https://choosealicense.com/no-license/). I assume the site wouldn't say its legal advice is necessarily sound but to me it makes sense.

I guess the safe way to approach this would be to tag all committers here and have them write that they explicitly grant the MIT license to any work they've contributed.

If that sounds like too much of a hassle, I understand.

**Comment by leehambley** [comment]
Capistrano opened a "change he license" issue and required all contributers
to👍. We had a few hundred so it took a while, the ones who didn't get back
to us, we rewrote those parts.

On 23 Oct 2017 22:04, "Clemens Kofler" <notifications@github.com> wrote:

According to choosealicense.com, "No License" means that you can't just add
a license later on (see https://choosealicense.com/no-license/). I assume
the site wouldn't say its legal advice is necessarily sound but to me it
makes sense.

I guess the safe way to approach this would be to tag all committers here
and have them write that they explicitly grant the MIT license to any work
they've contributed.

If that sounds like too much of a hassle, I understand.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/capistrano/chruby/pull/12#issuecomment-338779901>, or mute
the thread

**Comment by kirs** [comment]
@Aupajo @davekaro @igas @seenmyfate as contributors to capistrano-chruby, can I get your 👍 to get this project on MIT license (there was no license previously)? If you're ok with the license, please leave a comment. Thanks! ❤️

**Comment by seenmyfate** [comment]
@kirs definitely a 👍

**Comment by davekaro** [comment]
👍

**Comment by will-in-wi** [comment]
@Aupajo I think you are the only contributor left to approve this license change. Could you comment? Thanks!

**Comment by leoarnold** [comment]
@kirs could you please also add `gem.license       = "MIT"` to the Gemspec?

**Comment by Aupajo** [comment]
@will-in-wi Fine by me!

**Comment by will-in-wi** [comment]
Everyone has signed off!

**Pull request merged**
